### ISSUE TITLE
Build and serve yarn static with nginx

### ISSUE THREAD

**Issue by chrono2002** [cloudfoundry/yarn-cnb#5]
Please add feature to build static-only reactapp using yarn and server it with nginx.
Now there is no 'yarn build' step.

builder.toml like this:
```
[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.nginx"
version = "0.0.42"
```

heroku supports build steps, why cf isn't?
https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

**Comment by ryanmoran** [comment]
Support for "Heroku-style" build steps is implemented in the [nodejs-compat-cnb](https://github.com/cloudfoundry/nodejs-compat-cnb). This CNB exists purely for backwards compatibility and to bridge platform-specific features like the `heroku-prebuild` and `heroku-postbuild` fields.

You can include the nodejs-compat-cnb in your builder so that it is detected and run, ultimately adding support for build steps. Thanks!

**Comment by ForestEckhardt** [comment]
We're gonna close this as inactive. Please feel free to re-open if you have further issues.
